#读取格式如下：
#from utils.config import Config
#phone_num_a = Config().get('phone_num_a')
#password_a = Config().get('password_a')
#msg_1 = Config().get('msg_1')
#friends_name_2 = Config().get('friends_name_2') ..
#ios文本输入，需点击两次发送键

path: /Users/zoe/Desktop/Test_Framework_iOS/XConnect.ipa
url: http://localhost:4763/wd/hub

phone_num_a: 15951903161
password_a: 123456
phone_num_b: 15951903162
password_b: 123456
port_a: 4763
port_b: 4773

msg_1: 62你好
msg_2: 主页群，你好
msg_3: 会话页群，你好

new_group_1: 主页群
new_group_2: 会话页群

old_group_1: xuelei3161、xuelei3162、xuelei3163
old_group_2: xuelei3161、xuelei3162、xuelei3164

group_name_1: 本组成员
group_name_2: 测试组
group_name_2_1: 测试组1

friends_name_1: xuelei3161
friends_name_2: xuelei3162
friends_name_3: xuelei3163
friends_name_4: xuelei3164

button_name_1: 会话删除
button_name_2: 会话置顶
button_name_3: 取消置顶

time_out_small: 5

time_interval: 0.001
time_interval_times: 500


